-- 1. 판매 관리(Sales) 테이블 생성
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,                     -- 로그인 회원 ID (nullable)
    branch_name TEXT,                 -- 지점명
    user_name TEXT,                   -- 처리자(담당자) 이름
    user_branch TEXT,                 -- 처리자 지점
    customer_name TEXT,               -- 구매자 이름
    phone TEXT,                       -- 구매자 연락처
    address TEXT,                     -- 배송지 주소
    payment_method TEXT,              -- 결제 수단 (카드, 입금 등)
    quantity INTEGER,                 -- 총 수량
    deposit_amount INTEGER,           -- 총 결제/입금액
    order_details TEXT,               -- 주문 요약 내역 (예: 한글 K2 1개 등)
    age INTEGER,                      -- 구매자 연령 또는 생년월일
    needs_shipping BOOLEAN DEFAULT FALSE, -- 배송 여부
    privacy_agreed BOOLEAN DEFAULT FALSE, -- 개인정보 동의 여부
    marketing_agreed BOOLEAN DEFAULT FALSE, -- 마케팅 동의 여부
    payment_info JSONB,               -- 상세 결제 및 품목 정보 (JSON 저장)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 보안 정책(RLS) 설정
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- 모든 인증된 사용자가 자신의 지점 또는 전체 건을 조회할 수 있도록 설정 (정책에 따라 조정)
CREATE POLICY "Enable read for authenticated users" 
ON public.sales FOR SELECT 
TO authenticated 
USING (true);

-- 모든 인증된 사용자가 판매 기록을 삽입할 수 있도록 설정
CREATE POLICY "Enable insert for authenticated users" 
ON public.sales FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- 모든 인증된 사용자가 판매 기록을 수정할 수 있도록 설정
CREATE POLICY "Enable update for authenticated users" 
ON public.sales FOR UPDATE 
TO authenticated 
USING (true) 
WITH CHECK (true);
