-- 1. 상품 단가 테이블 생성
CREATE TABLE IF NOT EXISTS public.product_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series TEXT NOT NULL,          -- 시리즈 (K2, G1, S2 등)
    language TEXT NOT NULL,        -- 언어 (한글, 영문 등)
    price INTEGER NOT NULL,        -- 단가
    start_date DATE NOT NULL,      -- 적용 시작일
    end_date DATE,                 -- 적용 종료일 (현재 적용 중인 경우 NULL)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 검색 및 조건부 유니크 제약 (중요: PostgreSQL에서는 UNIQUE INDEX를 사용해야 하며, CONSTRAINT WHERE는 지원되지 않음)
-- 시리즈와 언어별로 현재 활성화된(end_date IS NULL) 데이터는 하나만 존재하도록 처리
CREATE UNIQUE INDEX IF NOT EXISTS product_prices_unique_active_idx 
ON public.product_prices (series, language) 
WHERE (end_date IS NULL);

-- 3. RLS 보안 정책 설정
ALTER TABLE public.product_prices ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 조회 가능하도록 허용
CREATE POLICY "Enable select for all users" 
ON public.product_prices FOR SELECT 
USING (true);

-- 모든 인증된 사용자가 모든 작업을 수행하도록 허용 (운영 환경에 맞춰 보안 강화 가능)
CREATE POLICY "Enable all for authenticated users" 
ON public.product_prices FOR ALL 
TO authenticated 
USING (true) 
WITH CHECK (true);
